name: DynamicShopGUI
version: '1.2-BETA'
main: com.Lino.dynamicShopGUI.DynamicShopGUI
api-version: '1.21'
depend: [Vault]
authors: [Lino]
description: Dynamic shop plugin with supply and demand pricing

commands:
  shop:
    description: Opens the dynamic shop GUI
    usage: /<command>
    permission: dynamicshop.use

permissions:
  dynamicshop.use:
    description: Allows players to use the shop
    default: true