name: DynamicShopGUI
version: 1.0.3-BETA
main: com.Lino.dynamicShopGUI.DynamicShopGUI
api-version: 1.20
author: Lino
description: A dynamic shop plugin with GUI

commands:
  shop:
    description: Open the shop menu
    usage: /shop
    permission: dynamicshop.use
  sell:
    description: Sell items to the shop
    usage: /sell <hand/all>
    permission: dynamicshop.sell
  sellchest:
    description: Get an auto-sell chest
    usage: /sellchest <player> <amount>
    permission: dynamicshop.admin

permissions:
  dynamicshop.use:
    description: Allows players to use the shop
    default: true
  dynamicshop.sell:
    description: Allows players to use the /sell command
    default: true
  dynamicshop.admin:
    description: Allows access to admin commands
    default: op